version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: url-shortener-database # Nome mais claro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
